openapi: 3.0.4
info:
  title: Text Lemmatizer
  description: Lemmatizer is a simple tool for lemmatizing text. It returns the lemmatized text.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.9
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
- url: https://api.apiverve.com/
paths:
  /v1/lemmatizer:
    post:
      summary: Lemmatize Text
      description: Lemmatizer is a simple tool for lemmatizing text. It returns the lemmatized text.
      operationId: lemmatizer
      parameters: []
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: string
                    description: data
              example:
                status: ok
                error: 
                data:
                  found: 3
                  lemmas:
                    cat: 1
                    ran: 1
                    door: 2
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occured, try again later
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                  description: The text to lemmatize
                  example: The cats ran from door to door
              required:
              - text
              example:
                text: The cats ran from door to door
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
- api_key: []
